FROM ubuntu:24.10

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
  && apt-get install -y pipx curl git \
  && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/buidly/onefinity-testnet-validators /opt/
WORKDIR /opt/
RUN /opt/download.sh
ENV PATH=$PATH:/usr/local/go/bin
RUN tar -C /usr/local -xzf go-onefinity.tar.gz  && rm go-onefinity.tar.gz
RUN cp /usr/local/go/pkg/mod/github.com/buidly/mx-evm-chain-vm-go@v0.0.0-20241218192919-285df70148f7/wasmer2/libvmexeccapi.so /usr/local/lib/ \
 && cp /usr/local/go/pkg/mod/github.com/buidly/mx-evm-chain-vm-go@v0.0.0-20241218192919-285df70148f7/wasmer/libwasmer_linux_amd64.so /usr/local/lib/ \
 && ldconfig
RUN pipx install multiversx-sdk-cli --force \
 &&  ln -s $(which mxpy) /usr/local/bin/mxpy
 
ENV PATH=$PATH:/root/.local/bin

RUN mxpy config set default_address_hrp one \
 && mxpy config dump \
 && rm /opt/mxpy
 
ADD generate-validator-key.sh /opt/onefinity-utils
ADD generate-wallet-key.sh /opt/onefinity-utils
ADD stake.sh /opt/onefinity-utils
ADD entrypoint.sh /opt/onefinity
RUN chmod +x /opt/onefinity-utils/generate-validator-key.sh 
RUN chmod +x /opt/onefinity-utils/generate-wallet-key.sh
RUN chmod +x /opt/onefinity/entrypoint.sh
RUN chmod +x /opt/onefinity-utils/stake.sh
ADD validator.json /opt/onefinity/config
WORKDIR /opt/onefinity
CMD ["/opt/onefinity/entrypoint.sh"]
